import { PluginConfig } from './config-types';

export const DEFAULT_CONFIG: PluginConfig = {
  enabled: true,
  transport: {
    mode: 'auto',
    lockPath: '.event-server/transport.lock',
    socketPath: '.event-server/transport.sock',
    lockStaleMs: 15000,
    heartbeatMs: 5000,
    relayTimeoutMs: 1500,
    reconnectBackoffMs: 250,
    maxPendingEvents: 2000,
    maxPayloadBytes: 1024 * 1024,
    authToken: undefined,
    dedupeTtlMs: 60000,
    semanticDedupeEnabled: true,
  },
  webhooks: [],
  filters: {
    includeTypes: [],
    excludeTypes: [],
  },
  retry: {
    maxAttempts: 3,
    initialDelayMs: 1000,
    maxDelayMs: 30000,
    backoffMultiplier: 2,
  },
  queue: {
    maxSize: 1000,
    flushIntervalMs: 5000,
    persistToDisk: false,
  },
  logging: {
    debug: false,
    logSuccess: false,
    logErrors: true,
    logQueue: false,
  },
  status: {
    workingWindowMs: 30_000,
    sleepingWindowMs: 10 * 60_000,
    tickIntervalMs: 5_000,
    subagentIdleWindowMs: 5 * 60_000,
  },
  redaction: {
    enabled: false,
    replacement: '[REDACTED]',
    fields: [
      'content',
      'newContent',
      'originalContent',
      'transcript',
      'normalizedText',
      'params',
      'arguments',
      'token',
      'apiKey',
      'api_key',
      'authorization',
      'authToken',
      'password',
      'secret',
    ],
  },
  privacy: {
    payloadMode: 'metadata',
  },
  eventLog: {
    enabled: true,
    path: '.event-server/events.ndjson',
    maxFileSizeMb: 30,
    format: 'full-json',
    minLevel: 'debug',
    includeRuntimeLogs: true,
  },
  security: {
    ws: {
      bindAddress: '127.0.0.1',
      requireAuth: false,
      authToken: undefined,
      allowedOrigins: [],
      allowedIps: [],
    },
    hmac: {
      enabled: false,
      secret: undefined,
      secretFilePath: '.event-plugin-hmac.secret',
      algorithm: 'sha256',
    },
  },
  correlationIdHeader: 'X-Correlation-ID',
  webhookTimeoutMs: 10000,
  hookBridge: {
    enabled: false,
    dryRun: false,
    allowedActionDirs: [],
    localScriptDefaults: {
      timeoutMs: 10000,
      maxPayloadBytes: 65536,
    },
    actions: {},
    rules: [],
    toolGuard: {
      enabled: false,
      dryRun: false,
      timeoutMs: 15000,
      onError: 'allow',
      scopeKeyBy: 'tool_and_params',
      retryBackoffMs: 10000,
      retryBackoffReason: 'Retry blocked. Back off briefly before retrying this tool call.',
      approvalCacheTtlMs: 60000,
      stopOnMatchDefault: false,
      redaction: {
        enabled: false,
        replacement: '[REDACTED]',
        fields: [
          'content',
          'newContent',
          'originalContent',
          'transcript',
          'normalizedText',
          'params',
          'arguments',
          'token',
          'apiKey',
          'api_key',
          'authorization',
          'authToken',
          'password',
          'secret',
        ],
      },
      rules: [],
    },
    runtime: {
      maxPendingEvents: 1000,
      concurrency: 8,
      dropPolicy: 'drop_oldest',
    },
    telemetry: {
      highWatermarks: [70, 90, 100],
      slowActionMs: 2000,
      failureRateWindowMs: 60000,
      failureRateThresholdPct: 20,
      failureRateMinSamples: 10,
      saturationWindowMs: 10000,
    },
  },
};
